### PR TITLE
Largely fixes issue with feedback viewing.

### PR DESCRIPTION
**Pull request by scriptbae**
Professor view now successfully displays feedback, with some
inconsistencies. A new issue will be opened to document this.

A preliminary fix for #29. An extensive overhaul of the implementation of the API at `/viewFeedBack` is included in this, spanning all three layers of the application, including `backend.py`, `dbhandler.py`, and `manage.js`, although the original database query has not been modified.

This has led to a subsequent issue, where the database backend will pull feedback about unrelated TAs (although I suspect this is a misunderstanding on my part because of the distinction between course sections and DGD sections, which is very ambiguous internally).

Please leave a comment explaining whether this is an issue which should be addressed, or whether the sections referred to in the "View feedback" view refer to course sections which may have multiple DGD sections.

Additional details:

- The UI is not fully implemented. Table headers are missing in-browser, and while the payload does segregate feedback by TA, the end result is rendered as a single (non-separated) table. This will be addressed as part of #12 unless deemed immediately important.

### CODE REVIEW

**Comment by scriptbae** [comment]
I'll try to keep future commits smaller. This one is nearly 300 changed lines because I dropped the ball on creating a feature branch, which I'll be using going forward.

**Comment by scriptbae** [comment]
10f2c4c Adds table headers and makes it clear when sections are separate (although still displays multiple sections simultaneously).

**Comment by scriptbae** [comment]
753ee58 Implements a fix for the ambiguous section issue.

**Review by cannotparse — APPROVED** [review]
Looks great

**Pull request merged**
